# Generated by Django 5.2.8 on 2025-11-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
